services:
  - type: web
    name: iteracion0-nextadmin
    env: node
    plan: free
    rootDir: "Iteración 0/Desarrollo/nextadmin-1.2.x/nextadmin-nextjs-pro-v2-main"
    autoDeploy: true
    buildCommand: npm ci && npx prisma generate && npm run build
    startCommand: npm run start -- -p $PORT
    envVars:
      - key: NODE_VERSION
        value: "20"
      - key: NEXT_TELEMETRY_DISABLED
        value: "1"
      # Si no vas a usar Postgres todavía, usa SQLite embebido (archivo incluido en el repo)
      - key: DATABASE_URL
        value: "file:./prisma/dev.db"
    healthCheckPath: /
